import { Application, Task, StudyPlan, Credential, UserProfile } from '../types/index.ts';
import { getFutureDateString, getTodayString } from './date.ts';

export const initialProfile: UserProfile = {
  name: '지현명',
  email: 'hyunmyungji@gmail.com',
  targetRole: '소프트웨어 엔지니어 (SW / AI / 백엔드)',
  avatarInitials: '현명',
};

export const initialApplications: Application[] = [
  {
    id: 'app-1',
    company: '네이버 (NAVER)',
    position: '클라우드 플랫폼 백엔드 개발자',
    title: '2026 신입/경력 소프트웨어 엔지니어 공개채용',
    deadline: getFutureDateString(4),
    stage: '서류합격',
    writtenTestDate: getFutureDateString(10),
    interviewDate: getFutureDateString(22),
    replyDeadline: getFutureDateString(2),
    location: '경기 성남시 분당구 1784',
    memo: '서류 합격 발표 완료! 1차 온라인 코딩테스트 및 전공 CS 지필평가 대비 중. 프로그래머스 레벨 3-4 위주 복습 필요.',
    subjects: ['알고리즘 코딩테스트', '운영체제/네트워크', '데이터베이스 최적화'],
    requiredDocuments: [
      { name: '이력서 및 포트폴리오 PDF', checked: true },
      { name: '어학 성적 증명서(TOEIC/OPIc)', checked: true },
      { name: '대학교 졸업/성적 증명서', checked: false },
      { name: '경력/프로젝트 기술서', checked: true },
    ],
    priority: 'high',
    createdAt: '2026-08-20',
    updatedAt: '2026-09-02',
  },
  {
    id: 'app-2',
    company: '현대자동차',
    position: '자율주행 인포테인먼트 SW 연구원',
    title: 'R&D본부 SW부문 하반기 신입 채용',
    deadline: getFutureDateString(2),
    stage: '서류접수',
    writtenTestDate: getFutureDateString(14),
    interviewDate: getFutureDateString(28),
    replyDeadline: '',
    location: '서울 양재동 본사 / 남양연구소',
    memo: '자기소개서 3번 항목(도전적 프로젝트 협업 경험) 수치 기반으로 가다듬기. 자율주행 CAN 통신 및 C++ 최적화 경험 강조.',
    subjects: ['소프티어 코딩테스트', 'C/C++ 자료구조', '임베디드 리눅스 기초'],
    requiredDocuments: [
      { name: '현대자동차 채용사이트 자소서', checked: true },
      { name: '깃허브 리포지토리 링크', checked: true },
      { name: '공인 어학 성적표', checked: false },
    ],
    priority: 'high',
    createdAt: '2026-08-28',
    updatedAt: '2026-09-05',
  },
  {
    id: 'app-3',
    company: '토스 (Viva Republica)',
    position: '서버 플랫폼 엔지니어 (Server Platform)',
    title: '토스 커뮤니티 전 직군 상시 채용',
    deadline: getFutureDateString(12),
    stage: '필기/코딩테스트',
    writtenTestDate: getFutureDateString(5),
    interviewDate: getFutureDateString(18),
    replyDeadline: getFutureDateString(3),
    location: '서울 강남구 테헤란로 아크플레이스',
    memo: '과제 전형 안내 메일 수신 완료. 대용량 트래픽 동시성 제어 및 분산 트랜잭션 설계가 핵심 평가 포인트.',
    subjects: ['Kotlin/Java Spring Boot', 'Kafka/Redis', 'MSA 아키텍처'],
    requiredDocuments: [
      { name: '자유 양식 이력서', checked: true },
      { name: '오픈소스 기여 내역', checked: false },
    ],
    priority: 'high',
    createdAt: '2026-08-15',
    updatedAt: '2026-09-08',
  },
  {
    id: 'app-4',
    company: '삼성전자 DX부문',
    position: 'SW 개발 (AI 플랫폼 엔지니어링)',
    title: '2026년 하반기 3급 신입사원 채용',
    deadline: getFutureDateString(18),
    stage: '1차면접',
    writtenTestDate: getFutureDateString(-5),
    interviewDate: getFutureDateString(9),
    replyDeadline: '',
    location: '경기 수원시 영통구 삼성디지털시티',
    memo: 'SW 역량테스트 합격 완료. 직무역량 면접에서 시스템 아키텍처 다이어그램 및 임원면접 인성 질문 대비 필요.',
    subjects: ['SW 역량테스트(완료)', '직무 기술면접', '창의성 면접'],
    requiredDocuments: [
      { name: '삼성 채용포털 에세이', checked: true },
      { name: '취득 자격증 사본', checked: true },
      { name: '건강검진 문진표', checked: false },
    ],
    priority: 'medium',
    createdAt: '2026-08-10',
    updatedAt: '2026-09-09',
  },
  {
    id: 'app-5',
    company: '카카오 (Kakao)',
    position: '인공지능 서비스 백엔드 개발',
    title: '카카오 테크 신입 블라인드 공채',
    deadline: getFutureDateString(25),
    stage: '2차/최종면접',
    writtenTestDate: getFutureDateString(-12),
    interviewDate: getFutureDateString(15),
    replyDeadline: '',
    location: '경기 성남시 분당구 판교역원',
    memo: '컬처핏 면접 및 최종 임원 인터뷰. 카카오 크루로서의 협업 철학 및 자기주도적 문제해결 경험 정리.',
    subjects: ['컬처핏 면접', '기술 심층 면접'],
    requiredDocuments: [
      { name: '포트폴리오 최종본', checked: true },
      { name: '추천서(선택)', checked: false },
    ],
    priority: 'high',
    createdAt: '2026-08-01',
    updatedAt: '2026-09-10',
  },
];

export const initialTasks: Task[] = [
  {
    id: 'task-1',
    applicationId: 'app-2',
    applicationName: '현대자동차',
    title: '자기소개서 3번 항목 마감 전 최종 퇴고 및 제출',
    category: '서류',
    dueDate: getFutureDateString(1),
    completed: false,
    priority: 'high',
    createdAt: '2026-09-08',
  },
  {
    id: 'task-2',
    applicationId: 'app-1',
    applicationName: '네이버 (NAVER)',
    title: '프로그래머스 고득점 Kit 그래프/DP 5문제 풀이',
    category: '필기',
    dueDate: getFutureDateString(2),
    completed: false,
    priority: 'high',
    createdAt: '2026-09-09',
  },
  {
    id: 'task-3',
    applicationId: 'app-3',
    applicationName: '토스 (Viva Republica)',
    title: 'Redis 동시성 분산락(Redisson) 구현 과제 테스트 케이스 작성',
    category: '필기',
    dueDate: getFutureDateString(3),
    completed: false,
    priority: 'high',
    createdAt: '2026-09-09',
  },
  {
    id: 'task-4',
    applicationId: 'app-4',
    applicationName: '삼성전자 DX부문',
    title: '직무면접 1분 자기소개 & 프로젝트 아키텍처 다이어그램 인쇄',
    category: '면접',
    dueDate: getFutureDateString(4),
    completed: false,
    priority: 'normal',
    createdAt: '2026-09-10',
  },
  {
    id: 'task-5',
    applicationId: 'app-1',
    applicationName: '네이버 (NAVER)',
    title: '학교 포털에서 영문 졸업예정증명서 및 성적표 PDF 발급',
    category: '서류',
    dueDate: getFutureDateString(5),
    completed: true,
    priority: 'normal',
    createdAt: '2026-09-07',
  },
  {
    id: 'task-6',
    title: '정보처리기사 실기 기출 3개년 오답노트 정리',
    category: '공통',
    dueDate: getFutureDateString(6),
    completed: false,
    priority: 'normal',
    createdAt: '2026-09-06',
  },
];

export const initialStudyPlans: StudyPlan[] = [
  {
    id: 'plan-1',
    applicationId: 'app-1',
    examName: '네이버 1차 코딩테스트 및 CS 필기시험',
    examDate: getFutureDateString(10),
    targetScoreOrRank: '상위 10% (3문제 완풀 + CS 85점 이상)',
    weekdayHours: 4,
    weekendHours: 7,
    subjects: [
      { name: '알고리즘 (DP, 그래프, 최단거리)', importance: 5, currentLevel: '중급' },
      { name: '운영체제 (가상메모리, 프로세스/스레드)', importance: 4, currentLevel: '상급' },
      { name: '네트워크 (TCP 3-way, HTTP 2/3, REST)', importance: 4, currentLevel: '중급' },
      { name: '데이터베이스 (B-Tree 인덱스, 트랜잭션 격리)', importance: 4, currentLevel: '중급' },
    ],
    availableDays: [1, 2, 3, 4, 5, 6, 0],
    excludedDates: [],
    days: [
      {
        date: getTodayString(),
        dayOfWeek: '오늘',
        blocks: [
          { id: 'b-1', subject: '알고리즘', topic: '다익스트라 & 벨만포드 핵심 유형 3선', hours: 2, completed: true },
          { id: 'b-2', subject: '운영체제', topic: '페이지 교체 알고리즘(LRU) & 문맥 교환 원리', hours: 1.5, completed: false },
          { id: 'b-3', subject: '데이터베이스', topic: '인덱스 풀스캔 vs 레인지스캔 실행계획 분석', hours: 1, completed: false },
        ],
      },
      {
        date: getFutureDateString(1),
        dayOfWeek: '내일',
        blocks: [
          { id: 'b-4', subject: '알고리즘', topic: '카카오/네이버 기출 시뮬레이션 구현 2문제', hours: 2.5, completed: false },
          { id: 'b-5', subject: '네트워크', topic: 'TLS 핸드셰이크 과정 및 CORS 사전요청 분석', hours: 1.5, completed: false },
        ],
      },
      {
        date: getFutureDateString(2),
        dayOfWeek: '모레',
        blocks: [
          { id: 'b-6', subject: '알고리즘', topic: '투포인터 & 슬라이딩 윈도우 심화', hours: 2, completed: false },
          { id: 'b-7', subject: '데이터베이스', topic: 'MVCC 및 락(Shared, Exclusive) 메커니즘', hours: 2, completed: false },
        ],
      },
      {
        date: getFutureDateString(3),
        dayOfWeek: 'D-7',
        blocks: [
          { id: 'b-8', subject: '종합 모의고사', topic: '실전 모의 코딩테스트 3시간 타이머 실전 연습', hours: 3.5, completed: false },
          { id: 'b-9', subject: '오답 분석', topic: '시간복잡도 O(NlogN) 최적화 정리', hours: 1.5, completed: false },
        ],
      },
    ],
    createdAt: '2026-09-05',
    updatedAt: '2026-09-10',
  },
];

export const initialCredentials: Credential[] = [
  {
    id: 'cred-1',
    name: 'TOEIC (토익)',
    grade: '',
    score: '935점',
    issuer: 'YBM 한국TOEIC위원회',
    acquiredDate: '2025-05-15',
    expiresAt: '2027-05-15',
    memo: '대부분의 공기업/대기업 어학 기준 완벽 충족 (유효기간 넉넉함)',
  },
  {
    id: 'cred-2',
    name: 'OPIc (오픽)',
    grade: 'AL (Advanced Low)',
    score: '',
    issuer: 'ACTFL / 멀티캠퍼스',
    acquiredDate: '2025-08-20',
    expiresAt: '2027-08-20',
    memo: '삼성전자 및 외국계 기술 기업 서류 우대 가점',
  },
  {
    id: 'cred-3',
    name: '정보처리기사',
    grade: '최종 합격',
    score: '',
    issuer: '한국산업인력공단',
    acquiredDate: '2025-11-28',
    expiresAt: '',
    memo: '국가공인 정보기술 기사 자격증 (영구 유효)',
  },
  {
    id: 'cred-4',
    name: 'SQLD (SQL 개발자)',
    grade: '합격',
    score: '84점',
    issuer: '한국데이터산업진흥원',
    acquiredDate: '2026-03-12',
    expiresAt: '2028-03-12',
    memo: '데이터 모델링 및 SQL 튜닝 기초 자격',
  },
];
