import { Application, Task, StudyPlan, Credential, UserProfile } from '../types/index.ts';
import { getFutureDateString, getTodayString } from './date.ts';
import { VISUAL_SAMPLE_DOCS } from './samplePosters.ts';
import { createInterviewSmsSvg, createFinalNoticeSvg } from './sampleNotices.ts';

const samsungDoc = VISUAL_SAMPLE_DOCS.find(d => d.id === 'samsung-dx');
const tossDoc = VISUAL_SAMPLE_DOCS.find(d => d.id === 'toss-banking');
const opicDoc = VISUAL_SAMPLE_DOCS.find(d => d.id === 'opic-score');
const ticketDoc = VISUAL_SAMPLE_DOCS.find(d => d.id === 'exam-ticket-samsung');

export const initialProfile: UserProfile = {
  name: '지현명',
  email: 'hyunmyungji@gmail.com',
  targetRole: '소프트웨어 엔지니어 (SW / AI / 백엔드)',
  avatarInitials: '현명',
};

export const initialApplications: Application[] = [
  {
    id: 'app-1',
    company: '네이버 (NAVER)',
    position: '클라우드 플랫폼 백엔드 개발자',
    title: '2026 신입/경력 소프트웨어 엔지니어 공개채용',
    deadline: getFutureDateString(4),
    stage: '서류합격',
    writtenTestDate: getFutureDateString(10),
    interviewDate: getFutureDateString(22),
    replyDeadline: getFutureDateString(2),
    location: '경기 성남시 분당구 1784',
    memo: '서류 합격 발표 완료! 1차 온라인 코딩테스트 및 전공 CS 지필평가 대비 중. 프로그래머스 레벨 3-4 위주 복습 필요.',
    subjects: ['알고리즘 코딩테스트', '운영체제/네트워크', '데이터베이스 최적화'],
    imageUrl: ticketDoc?.previewDataUrl,
    stageNotices: [
      {
        id: 'notice-app1-sms',
        stage: '서류합격',
        noticeType: 'sms',
        title: '[서류 합격] 1차 직무면접 안내 문자 (SMS)',
        sender: '[NAVER 채용팀]',
        receivedDate: '2026-09-02',
        interviewDate: getFutureDateString(22),
        location: '경기 성남시 분당구 1784 사옥 4층 인터뷰룸',
        locationDetail: '신분당선/수인분당선 정자역 3번 출구 도보 6분 (1784 로비 안내데스크 출입증 수령)',
        dressCode: '단정한 자율 복장 (비즈니스 캐주얼 / 셔츠)',
        checklistItems: [
          { id: 'app1-chk-1', text: '본인 신분증 (주민등록증 또는 운전면허증 지참)', checked: true, category: '준비물' },
          { id: 'app1-chk-2', text: '포트폴리오 출력본 2부 및 깃허브 코드 아키텍처 요약', checked: true, category: '준비물' },
          { id: 'app1-chk-3', text: '1784 사옥 4층 인터뷰룸 위치 및 지하철 정자역 이동 경로 사전 확인', checked: true, category: '시험장소' },
          { id: 'app1-chk-4', text: '면접 시작 20분 전(13:40) 1층 로비 도착 및 방문증 수령', checked: false, category: '시험장소' },
          { id: 'app1-chk-5', text: '단정한 자율 복장 착용 점검', checked: false, category: '복장/기타' },
        ],
        content: `[NAVER] 안녕하세요 지현명님, 클라우드 플랫폼 백엔드 개발자 서류 전형 합격을 진심으로 축하드립니다.\n\n■ 1차 직무역량 기술면접 안내\n- 일시: 2026년 10월 4일(일) 14:00 (15분 전 도착 대기)\n- 방식: NAVER 1784 사옥 4층 인터뷰룸 대면 면접\n- 면접 내용: CS 기본기, 제출 포트폴리오 코드 아키텍처 리뷰, 직무 역량 검증\n- 준비물: 신분증(주민등록증 또는 운전면허증)\n- 복장: 단정한 자율 복장\n\n상세한 안내 및 참석 확인은 네이버 채용 포털을 확인해 주시기 바랍니다.`,
        imageUrl: createInterviewSmsSvg('네이버 (NAVER)', '2026.10.04 (일) 14:00', 'NAVER 1784 사옥 4층 인터뷰룸'),
        imageUrls: [
          createInterviewSmsSvg('네이버 (NAVER)', '2026.10.04 (일) 14:00', 'NAVER 1784 사옥 4층 인터뷰룸'),
          createFinalNoticeSvg('네이버 (NAVER)', '2026.10.04 (일) 14:00', 'NAVER 1784 사옥 4층 기술면접실 (오시는 길 및 유의사항)'),
        ],
        notes: 'CS 전공지식(OS, 네트워크, DB 트랜잭션) 및 깃허브 코드 리뷰 준비',
        createdAt: '2026-09-02',
      },
    ],
    requiredDocuments: [
      { name: '이력서 및 포트폴리오 PDF', checked: true },
      { name: '어학 성적 증명서(TOEIC/OPIc)', checked: true },
      { name: '대학교 졸업/성적 증명서', checked: false },
      { name: '경력/프로젝트 기술서', checked: true },
    ],
    priority: 'high',
    createdAt: '2026-08-20',
    updatedAt: '2026-09-02',
  },
  {
    id: 'app-2',
    company: '현대자동차',
    position: '자율주행 인포테인먼트 SW 연구원',
    title: 'R&D본부 SW부문 하반기 신입 채용',
    deadline: getFutureDateString(2),
    stage: '서류접수',
    writtenTestDate: getFutureDateString(14),
    interviewDate: getFutureDateString(28),
    replyDeadline: '',
    location: '서울 양재동 본사 / 남양연구소',
    memo: '자기소개서 3번 항목(도전적 프로젝트 협업 경험) 수치 기반으로 가다듬기. 자율주행 CAN 통신 및 C++ 최적화 경험 강조.',
    subjects: ['소프티어 코딩테스트', 'C/C++ 자료구조', '임베디드 리눅스 기초'],
    requiredDocuments: [
      { name: '현대자동차 채용사이트 자소서', checked: true },
      { name: '깃허브 리포지토리 링크', checked: true },
      { name: '공인 어학 성적표', checked: false },
    ],
    priority: 'high',
    createdAt: '2026-08-28',
    updatedAt: '2026-09-05',
  },
  {
    id: 'app-3',
    company: '토스 (Viva Republica)',
    position: '서버 플랫폼 엔지니어 (Server Platform)',
    title: '토스 커뮤니티 전 직군 상시 채용',
    deadline: getFutureDateString(12),
    stage: '필기/코딩테스트',
    writtenTestDate: getFutureDateString(5),
    interviewDate: getFutureDateString(18),
    replyDeadline: getFutureDateString(3),
    location: '서울 강남구 테헤란로 아크플레이스',
    memo: '과제 전형 안내 메일 수신 완료. 대용량 트래픽 동시성 제어 및 분산 트랜잭션 설계가 핵심 평가 포인트.',
    subjects: ['Kotlin/Java Spring Boot', 'Kafka/Redis', 'MSA 아키텍처'],
    imageUrl: tossDoc?.previewDataUrl,
    requiredDocuments: [
      { name: '자유 양식 이력서', checked: true },
      { name: '오픈소스 기여 내역', checked: false },
    ],
    priority: 'high',
    createdAt: '2026-08-15',
    updatedAt: '2026-09-08',
  },
  {
    id: 'app-4',
    company: '삼성전자 DX부문',
    position: 'SW 개발 (AI 플랫폼 엔지니어링)',
    title: '2026년 하반기 3급 신입사원 채용',
    deadline: getFutureDateString(18),
    stage: '1차면접',
    writtenTestDate: getFutureDateString(-5),
    interviewDate: getFutureDateString(9),
    replyDeadline: '',
    location: '경기 수원시 영통구 삼성디지털시티',
    memo: 'SW 역량테스트 합격 완료. 직무역량 면접에서 시스템 아키텍처 다이어그램 및 임원면접 인성 질문 대비 필요.',
    subjects: ['SW 역량테스트(완료)', '직무 기술면접', '창의성 면접'],
    imageUrl: samsungDoc?.previewDataUrl,
    stageNotices: [
      {
        id: 'notice-app4-sms',
        stage: '1차면접',
        noticeType: 'sms',
        title: '[SW테스트 합격] 직무역량 & 창의성 면접 안내 문자',
        sender: '[삼성전자 채용팀 031-200-XXXX]',
        receivedDate: '2026-09-09',
        interviewDate: getFutureDateString(9),
        location: '경기 수원시 영통구 삼성디지털시티 인재개발원',
        locationDetail: '수원 사업장 인재개발원 서문 안내실 (수원역 4번 출구 셔틀버스 운행)',
        dressCode: '단정한 정장 또는 비즈니스 캐주얼 (넥타이 자율)',
        checklistItems: [
          { id: 'app4-chk-1', text: '삼성 채용포털 출력 수험표 지참', checked: true, category: '준비물' },
          { id: 'app4-chk-2', text: '본인 신분증 (주민등록증 / 운전면허증 지참)', checked: true, category: '준비물' },
          { id: 'app4-chk-3', text: '재학/졸업증명서 및 전학년 성적증명서 원본', checked: false, category: '준비물' },
          { id: 'app4-chk-4', text: '수원디지털시티 셔틀버스 탑승 위치 사전 확인', checked: true, category: '시험장소' },
          { id: 'app4-chk-5', text: '08:30 등록 마감 20분 전 시험장 도착 대기', checked: false, category: '시험장소' },
        ],
        content: `[삼성전자 DX부문] SW개발 3급 신입 채용 1차 면접 전형 안내\n\n지현명 지원자님, SW역량테스트 합격을 축하드립니다.\n직무역량 및 창의성 면접 전형 일정을 안내해 드립니다.\n\n- 일시: 2026년 9월 21일(월) 08:30 등록 (종일 진행)\n- 장소: 경기 수원시 영통구 삼성디지털시티 인재개발원\n- 준비물: 수험표, 신분증, 재학/졸업증명서\n- 복장: 정장 또는 비즈니스 캐주얼`,
        imageUrl: createInterviewSmsSvg('삼성전자 DX', '2026.09.21 (월) 08:30', '수원 삼성디지털시티 인재개발원'),
        notes: 'SW 문제풀이 코드 설명 및 PT 발표 연습',
        createdAt: '2026-09-09',
      },
    ],
    requiredDocuments: [
      { name: '삼성 채용포털 에세이', checked: true },
      { name: '취득 자격증 사본', checked: true },
      { name: '건강검진 문진표', checked: false },
    ],
    priority: 'medium',
    createdAt: '2026-08-10',
    updatedAt: '2026-09-09',
  },
  {
    id: 'app-5',
    company: '카카오 (Kakao)',
    position: '인공지능 서비스 백엔드 개발',
    title: '카카오 테크 신입 블라인드 공채',
    deadline: getFutureDateString(25),
    stage: '2차/최종면접',
    writtenTestDate: getFutureDateString(-12),
    interviewDate: getFutureDateString(15),
    replyDeadline: '',
    location: '경기 성남시 분당구 판교역원',
    memo: '컬처핏 면접 및 최종 임원 인터뷰. 카카오 크루로서의 협업 철학 및 자기주도적 문제해결 경험 정리.',
    stageMemos: {
      '서류접수': '카카오 개발 블로그 아티클 및 오픈소스 기여 사례 위주로 포트폴리오 구성 완료.',
      '서류합격': '서류 합격 통과! 1차 기술 인터뷰 코딩테스트 및 시스템 디자인 질문 집중 대비.',
      '1차면접': '1차 기술 인터뷰(CS 및 라이브 코딩): 동시성 제어 및 Kafka 메시지 큐 활용 경험 위주로 어필 성공.',
      '2차/최종면접': '카카오 크루 철학 및 가치관(충돌을 두려워하지 않는 자기주도성), 갈등 해결 사례, 향후 3년 기술 로드맵 철저 대비.',
    },
    subjects: ['컬처핏 면접', '기술 심층 면접'],
    stageNotices: [
      {
        id: 'notice-app5-first',
        stage: '1차면접',
        noticeType: 'sms',
        title: '[서류 합격] 1차 기술 인터뷰 화상 면접 안내 문자',
        sender: '[카카오 채용팀]',
        receivedDate: '2026-08-28',
        interviewDate: '2026-09-08 14:00',
        location: '온라인 화상 면접 (Google Meet)',
        locationDetail: '온라인 화상 회의실 링크 사전 접속 테스트 (면접 10분 전 대기)',
        dressCode: '단정한 자율 복장',
        checklistItems: [
          { id: 'app5-first-chk-1', text: '화상 카메라 및 마이크 음질 사전 점검', checked: true, category: '준비물' },
          { id: 'app5-first-chk-2', text: '본인 확인용 신분증 카메라 지참', checked: true, category: '준비물' },
          { id: 'app5-first-chk-3', text: '라이브 코딩 IDE 및 공유 화면 환경 세팅', checked: true, category: '시험장소' },
          { id: 'app5-first-chk-4', text: '조용하고 독립된 면접 공간 확보', checked: true, category: '시험장소' },
        ],
        content: `[카카오] 서류 전형 합격 및 1차 기술 인터뷰 안내\n\n지현명 지원자님, 카카오 신입 테크 공채 서류 전형 합격을 축하드립니다.\n1차 기술 인터뷰는 온라인 화상으로 진행됩니다.\n\n- 일시: 2026년 9월 8일(화) 14:00\n- 방식: 온라인 화상 면접 (면접관 2인, 60분 진행)\n- 내용: CS 기본기, 라이브 코딩 및 프로젝트 아키텍처 검증`,
        imageUrl: createInterviewSmsSvg('카카오 (Kakao)', '2026.09.08 (화) 14:00', '온라인 화상 면접 (Google Meet)'),
        notes: '1차 기술 인터뷰 CS 기본기 및 라이브 코딩 완료 (합격)',
        createdAt: '2026-08-28',
      },
      {
        id: 'notice-app5-final',
        stage: '2차/최종면접',
        noticeType: 'document',
        title: '[1차 면접 합격] 2차 최종 임원면접 공식 안내문',
        sender: '[카카오 인사팀 (HR)]',
        receivedDate: '2026-09-10',
        interviewDate: getFutureDateString(15),
        location: '경기 성남시 분당구 판교역원 카카오 아지트 7층 접견실',
        locationDetail: '신분당선 판교역 1번 출구 도보 2분 카카오 판교 아지트 (1층 인포데스크 출입증 수령)',
        dressCode: '비즈니스 캐주얼 또는 깔끔한 정장 (자율)',
        checklistItems: [
          { id: 'app5-chk-1', text: '대학교 졸업(예정)증명서 원본 및 공인 어학 성적표 사본', checked: true, category: '준비물' },
          { id: 'app5-chk-2', text: '본인 사진 부착 신분증 원본 (주민등록증 / 운전면허증)', checked: true, category: '준비물' },
          { id: 'app5-chk-3', text: '판교 아지트 1층 인포데스크 출입증 수령 (30분 전 도착 완료)', checked: false, category: '시험장소' },
          { id: 'app5-chk-4', text: '판교역 1번 출구 도보 동선 및 대기실 위치 사전 확인', checked: true, category: '시험장소' },
          { id: 'app5-chk-5', text: '임원 면접용 1분 자기소개 및 컬처핏 답변 최종 정리', checked: false, category: '복장/기타' },
        ],
        content: `[카카오] 1차 기술 인터뷰 합격 안내 및 2차 최종 컬처핏 면접 일정 안내문\n\n1차 기술 인터뷰에 최종 합격하셨습니다.\n2차 최종 인터뷰는 카카오 판교 아지트에서 대면으로 진행됩니다.\n\n- 면접 일시: 2026년 9월 27일(토) 15:30\n- 장소: 경기 성남시 판교 카카오 아지트 7층 접견실\n- 면접 형식: 임원 3인 / 지원자 1인 심층 면접 (40분 진행)\n- 지참 서류: 대학교 졸업(예정)증명서 원본, 공인 어학 성적표 사본\n- 안내 사항: 면접 시작 30분 전 1층 인포데스크에서 방문 출입증을 수령하시기 바랍니다.`,
        imageUrl: createFinalNoticeSvg('카카오 (Kakao)', '2026.09.27 (토) 15:30', '판교 카카오 아지트 7층 접견실'),
        imageUrls: [
          createFinalNoticeSvg('카카오 (Kakao)', '2026.09.27 (토) 15:30', '판교 카카오 아지트 7층 접견실'),
          createInterviewSmsSvg('카카오 (Kakao)', '2026.09.27 (토) 15:30', '판교 카카오 아지트 7층 인터뷰존 (방문안내)'),
        ],
        notes: '카카오 크루 철학 및 갈등 해결 사례, 향후 3년 기술 로드맵 답변 준비',
        createdAt: '2026-09-10',
      },
    ],
    requiredDocuments: [
      { name: '포트폴리오 최종본', checked: true },
      { name: '추천서(선택)', checked: false },
    ],
    priority: 'high',
    createdAt: '2026-08-01',
    updatedAt: '2026-09-10',
  },
];

export const initialTasks: Task[] = [
  {
    id: 'task-1',
    applicationId: 'app-2',
    applicationName: '현대자동차',
    title: '자기소개서 3번 항목 마감 전 최종 퇴고 및 제출',
    category: '서류',
    dueDate: getFutureDateString(1),
    completed: false,
    priority: 'high',
    createdAt: '2026-09-08',
  },
  {
    id: 'task-2',
    applicationId: 'app-1',
    applicationName: '네이버 (NAVER)',
    title: '프로그래머스 고득점 Kit 그래프/DP 5문제 풀이',
    category: '필기',
    dueDate: getFutureDateString(2),
    completed: false,
    priority: 'high',
    createdAt: '2026-09-09',
  },
  {
    id: 'task-3',
    applicationId: 'app-3',
    applicationName: '토스 (Viva Republica)',
    title: 'Redis 동시성 분산락(Redisson) 구현 과제 테스트 케이스 작성',
    category: '필기',
    dueDate: getFutureDateString(3),
    completed: false,
    priority: 'high',
    createdAt: '2026-09-09',
  },
  {
    id: 'task-4',
    applicationId: 'app-4',
    applicationName: '삼성전자 DX부문',
    title: '직무면접 1분 자기소개 & 프로젝트 아키텍처 다이어그램 인쇄',
    category: '면접',
    dueDate: getFutureDateString(4),
    completed: false,
    priority: 'normal',
    createdAt: '2026-09-10',
  },
  {
    id: 'task-5',
    applicationId: 'app-1',
    applicationName: '네이버 (NAVER)',
    title: '학교 포털에서 영문 졸업예정증명서 및 성적표 PDF 발급',
    category: '서류',
    dueDate: getFutureDateString(5),
    completed: true,
    priority: 'normal',
    createdAt: '2026-09-07',
  },
  {
    id: 'task-6',
    title: '정보처리기사 실기 기출 3개년 오답노트 정리',
    category: '공통',
    dueDate: getFutureDateString(6),
    completed: false,
    priority: 'normal',
    createdAt: '2026-09-06',
  },
];

export const initialStudyPlans: StudyPlan[] = [
  {
    id: 'plan-1',
    applicationId: 'app-1',
    examName: '네이버 1차 코딩테스트 및 CS 필기시험',
    examDate: getFutureDateString(10),
    targetScoreOrRank: '상위 10% (3문제 완풀 + CS 85점 이상)',
    weekdayHours: 4,
    weekendHours: 7,
    subjects: [
      { name: '알고리즘 (DP, 그래프, 최단거리)', importance: 5, currentLevel: '중급' },
      { name: '운영체제 (가상메모리, 프로세스/스레드)', importance: 4, currentLevel: '상급' },
      { name: '네트워크 (TCP 3-way, HTTP 2/3, REST)', importance: 4, currentLevel: '중급' },
      { name: '데이터베이스 (B-Tree 인덱스, 트랜잭션 격리)', importance: 4, currentLevel: '중급' },
    ],
    availableDays: [1, 2, 3, 4, 5, 6, 0],
    excludedDates: [],
    days: [
      {
        date: getTodayString(),
        dayOfWeek: '오늘',
        blocks: [
          { id: 'b-1', subject: '알고리즘', topic: '다익스트라 & 벨만포드 핵심 유형 3선', hours: 2, completed: true },
          { id: 'b-2', subject: '운영체제', topic: '페이지 교체 알고리즘(LRU) & 문맥 교환 원리', hours: 1.5, completed: false },
          { id: 'b-3', subject: '데이터베이스', topic: '인덱스 풀스캔 vs 레인지스캔 실행계획 분석', hours: 1, completed: false },
        ],
      },
      {
        date: getFutureDateString(1),
        dayOfWeek: '내일',
        blocks: [
          { id: 'b-4', subject: '알고리즘', topic: '카카오/네이버 기출 시뮬레이션 구현 2문제', hours: 2.5, completed: false },
          { id: 'b-5', subject: '네트워크', topic: 'TLS 핸드셰이크 과정 및 CORS 사전요청 분석', hours: 1.5, completed: false },
        ],
      },
      {
        date: getFutureDateString(2),
        dayOfWeek: '모레',
        blocks: [
          { id: 'b-6', subject: '알고리즘', topic: '투포인터 & 슬라이딩 윈도우 심화', hours: 2, completed: false },
          { id: 'b-7', subject: '데이터베이스', topic: 'MVCC 및 락(Shared, Exclusive) 메커니즘', hours: 2, completed: false },
        ],
      },
      {
        date: getFutureDateString(3),
        dayOfWeek: 'D-7',
        blocks: [
          { id: 'b-8', subject: '종합 모의고사', topic: '실전 모의 코딩테스트 3시간 타이머 실전 연습', hours: 3.5, completed: false },
          { id: 'b-9', subject: '오답 분석', topic: '시간복잡도 O(NlogN) 최적화 정리', hours: 1.5, completed: false },
        ],
      },
    ],
    createdAt: '2026-09-05',
    updatedAt: '2026-09-10',
  },
];

export const initialCredentials: Credential[] = [
  {
    id: 'cred-1',
    name: 'TOEIC (토익)',
    grade: '',
    score: '935점',
    issuer: 'YBM 한국TOEIC위원회',
    acquiredDate: '2025-05-15',
    expiresAt: '2027-05-15',
    memo: '대부분의 공기업/대기업 어학 기준 완벽 충족 (유효기간 넉넉함)',
  },
  {
    id: 'cred-2',
    name: 'OPIc (오픽)',
    grade: 'AL (Advanced Low)',
    score: '',
    issuer: 'ACTFL / 멀티캠퍼스',
    acquiredDate: '2025-08-20',
    expiresAt: '2027-08-20',
    imageUrl: opicDoc?.previewDataUrl,
    memo: '삼성전자 및 외국계 기술 기업 서류 우대 가점',
  },
  {
    id: 'cred-3',
    name: '정보처리기사',
    grade: '최종 합격',
    score: '',
    issuer: '한국산업인력공단',
    acquiredDate: '2025-11-28',
    expiresAt: '',
    memo: '국가공인 정보기술 기사 자격증 (영구 유효)',
  },
  {
    id: 'cred-4',
    name: 'SQLD (SQL 개발자)',
    grade: '합격',
    score: '84점',
    issuer: '한국데이터산업진흥원',
    acquiredDate: '2026-03-12',
    expiresAt: '2028-03-12',
    memo: '데이터 모델링 및 SQL 튜닝 기초 자격',
  },
];
